# Para baixar a imagem base 
FROM nginx

# o destino para onde será copiado é o contexto do proprio nginx
# oara saber o destino usar o cat /etc/nginx/conf.d/default.conf e verificar o root
COPY index.html /usr/share/nginx/html

